services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v15.11.1
    container_name: gitlab-runner-v15.11.1
    restart: always
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-runner-net

networks:
  gitlab-runner-net:
    driver: bridge